// <auto-generated />
using AtosProjetoFinal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtosProjetoFinal.Migrations
{
    [DbContext(typeof(CharacterSheetContext))]
    [Migration("20220713002529_addingClassName")]
    partial class addingClassName
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AtosProjetoFinal.Models.Ancestry", b =>
                {
                    b.Property<int>("ancestryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ancestryID"), 1L, 1);

                    b.Property<string>("ancestryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trait1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trait2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trait3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ancestryID");

                    b.ToTable("Ancestry");
                });

            modelBuilder.Entity("AtosProjetoFinal.Models.Armor", b =>
                {
                    b.Property<int>("armorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("armorID"), 1L, 1);

                    b.Property<int>("armorBulk")
                        .HasColumnType("int");

                    b.Property<string>("armorDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("armorGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("armorName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("armorProtectionValue")
                        .HasColumnType("int");

                    b.HasKey("armorID");

                    b.ToTable("Armor");
                });

            modelBuilder.Entity("AtosProjetoFinal.Models.Character", b =>
                {
                    b.Property<int>("characterID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("characterID"), 1L, 1);

                    b.Property<int>("ancestryID")
                        .HasColumnType("int");

                    b.Property<string>("background")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("characterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("classID")
                        .HasColumnType("int");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("expPoints")
                        .HasColumnType("int");

                    b.Property<int>("roleID")
                        .HasColumnType("int");

                    b.HasKey("characterID");

                    b.HasIndex("ancestryID");

                    b.HasIndex("classID");

                    b.HasIndex("roleID");

                    b.ToTable("Character");
                });

            modelBuilder.Entity("AtosProjetoFinal.Models.CharArmor", b =>
                {
                    b.Property<int>("charArmorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("charArmorID"), 1L, 1);

                    b.Property<int>("armorID")
                        .HasColumnType("int");

                    b.Property<int>("characterID")
                        .HasColumnType("int");

                    b.HasKey("charArmorID");

                    b.HasIndex("armorID");

                    b.HasIndex("characterID");

                    b.ToTable("CharArmor");
                });

            modelBuilder.Entity("AtosProjetoFinal.Models.CharAttributes", b =>
                {
                    b.Property<int>("charAttributesID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("charAttributesID"), 1L, 1);

                    b.Property<int>("block")
                        .HasColumnType("int");

                    b.Property<int>("characterID")
                        .HasColumnType("int");

                    b.Property<int>("charisma")
                        .HasColumnType("int");

                    b.Property<int>("conviction")
                        .HasColumnType("int");

                    b.Property<int>("dexterity")
                        .HasColumnType("int");

                    b.Property<int>("evasion")
                        .HasColumnType("int");

                    b.Property<int>("intelligence")
                        .HasColumnType("int");

                    b.Property<int>("magic_def")
                        .HasColumnType("int");

                    b.Property<int>("perception")
                        .HasColumnType("int");

                    b.Property<int>("physique")
                        .HasColumnType("int");

                    b.Property<int>("reputation")
                        .HasColumnType("int");

                    b.Property<int>("spirit")
                        .HasColumnType("int");

                    b.Property<int>("stamina")
                        .HasColumnType("int");

                    b.HasKey("charAttributesID");

                    b.HasIndex("characterID");

                    b.ToTable("CharAttibutes");
                });

            modelBuilder.Entity("AtosProjetoFinal.Models.CharItem", b =>
                {
                    b.Property<int>("charItemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("charItemID"), 1L, 1);

                    b.Property<int>("characterID")
                        .HasColumnType("int");

                    b.Property<int>("itemID")
                        .HasColumnType("int");

                    b.HasKey("charItemID");

                    b.HasIndex("characterID");

                    b.HasIndex("itemID");

                    b.ToTable("CharItem");
                });

            modelBuilder.Entity("AtosProjetoFinal.Models.CharWeapon", b =>
                {
                    b.Property<int>("charWeaponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("charWeaponID"), 1L, 1);

                    b.Property<int>("characterID")
                        .HasColumnType("int");

                    b.Property<int>("weaponID")
                        .HasColumnType("int");

                    b.HasKey("charWeaponID");

                    b.HasIndex("characterID");

                    b.HasIndex("weaponID");

                    b.ToTable("CharWeapon");
                });

            modelBuilder.Entity("AtosProjetoFinal.Models.Class", b =>
                {
                    b.Property<int>("classID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("classID"), 1L, 1);

                    b.Property<string>("className")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("level1_ability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("level2_ability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("level3_ability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("classID");

                    b.ToTable("Class");
                });

            modelBuilder.Entity("AtosProjetoFinal.Models.Item", b =>
                {
                    b.Property<int>("itemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("itemID"), 1L, 1);

                    b.Property<int>("itemBulk")
                        .HasColumnType("int");

                    b.Property<string>("itemDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("itemGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("itemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("itemID");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("AtosProjetoFinal.Models.Role", b =>
                {
                    b.Property<int>("roleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("roleID"), 1L, 1);

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trait1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trait2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trait3")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("roleID");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("AtosProjetoFinal.Models.Weapon", b =>
                {
                    b.Property<int>("weaponID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("weaponID"), 1L, 1);

                    b.Property<string>("weaponDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("weaponGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("weaponName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("weaponRange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("weapongDmgType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("weaponID");

                    b.ToTable("Weapon");
                });

            modelBuilder.Entity("AtosProjetoFinal.Models.Character", b =>
                {
                    b.HasOne("AtosProjetoFinal.Models.Ancestry", "Ancestry")
                        .WithMany()
                        .HasForeignKey("ancestryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtosProjetoFinal.Models.Class", "CharClass")
                        .WithMany()
                        .HasForeignKey("classID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtosProjetoFinal.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("roleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ancestry");

                    b.Navigation("CharClass");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AtosProjetoFinal.Models.CharArmor", b =>
                {
                    b.HasOne("AtosProjetoFinal.Models.Armor", "Armor")
                        .WithMany()
                        .HasForeignKey("armorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtosProjetoFinal.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("characterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Armor");

                    b.Navigation("Character");
                });

            modelBuilder.Entity("AtosProjetoFinal.Models.CharAttributes", b =>
                {
                    b.HasOne("AtosProjetoFinal.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("characterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");
                });

            modelBuilder.Entity("AtosProjetoFinal.Models.CharItem", b =>
                {
                    b.HasOne("AtosProjetoFinal.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("characterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtosProjetoFinal.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("itemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("AtosProjetoFinal.Models.CharWeapon", b =>
                {
                    b.HasOne("AtosProjetoFinal.Models.Character", "Character")
                        .WithMany()
                        .HasForeignKey("characterID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtosProjetoFinal.Models.Weapon", "Weapon")
                        .WithMany()
                        .HasForeignKey("weaponID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("Weapon");
                });
#pragma warning restore 612, 618
        }
    }
}
